DROP TABLE IF EXISTS users;
GO

CREATE TABLE users
( id INT IDENTITY
, age INT
);
GO

INSERT INTO users (age) VALUES
(18);
GO

-- dirty read READ UNCOMMITTED

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRAN;
SELECT age FROM users WHERE id = 1;
WAITFOR DELAY '00:00:5';
SELECT age FROM users WHERE id = 1;
COMMIT;

SELECT age FROM users WHERE id = 1;
UPDATE users SET age = 18 WHERE id = 1;

--- Non-repeatable reads READ COMMITTED

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRAN;
SELECT age FROM users WHERE id = 1;
WAITFOR DELAY '00:00:5';
SELECT age FROM users WHERE id = 1;
COMMIT;

--- phantom reads REPEATABLE READ
--SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN T1;
SELECT * FROM users WHERE age BETWEEN 10 AND 30;
WAITFOR DELAY '00:00:5';
SELECT * FROM users WHERE age BETWEEN 10 AND 30;
COMMIT;

