/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendar;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author MarkG
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Calendar cal = new GregorianCalendar();
    int year;
    JPanel table;
    public MainFrame() {
        initComponents();
        jPanel1.setLayout(new GridLayout());
        
        table = new JPanel();
        table.setLayout(new GridLayout(3,4,7,12));
        jPanel1.add(table);
        table.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        year = cal.get(Calendar.YEAR);
        cal.set(Calendar.DAY_OF_YEAR,1);
        FillYear();

    }
    
    public void FillYear() {
        String[] months = {"January", "February", "March", "April", "May", "June", 
                           "July", "August", "September", "October", "November", "December"};
        
        for (int i = 0; i < 12; i++) {
            table.add(FillMonth(months[i]));
            cal.add(Calendar.MONTH, +1);
        }
        
    }
    
    public JPanel FillMonth(String month ) {
        String[] days_of_week = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};
        JPanel mon = new JPanel();
        JPanel mpanel = new JPanel();
        if ("January".equals(month)) {
            JButton left = new JButton("<");
            left.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    cal.set(Calendar.YEAR, cal.get(Calendar.YEAR)-1);
                    FillYear();
                    
                }
            });
            mpanel.add(left);        
        }
        JButton name_of_month = new JButton(month+" "+ cal.get(Calendar.YEAR));
        mpanel.add(name_of_month);
       
        if ("April".equals(month)) {
             JButton right = new JButton(">");
             mpanel.add(right);
                    
        }
          
        
       
        mon.setLayout(new BoxLayout(mon, BoxLayout.Y_AXIS));
        mpanel.setAlignmentX(Component.CENTER_ALIGNMENT);
        //name_of_month.setAlignmentX(Component.CENTER_ALIGNMENT);
        mon.add(mpanel);
        JPanel mdays = new JPanel();
        //mdays.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        int numberOfDays = cal.getActualMaximum(Calendar.DAY_OF_MONTH);
        int startDay =cal.get(Calendar.DAY_OF_WEEK)-1;
        if (startDay == 6)
             mdays.setLayout(new GridLayout(7,7,1,1));
        else
            mdays.setLayout(new GridLayout(6,7,1,1));
        for (int i = 0; i < days_of_week.length; i++) {
            mdays.add(new JLabel(days_of_week[i]));
        }
         while (startDay > 0) {
                mdays.add(new JLabel(" "));
                startDay--;
         }
        for (int i = 0; i < numberOfDays; i++) {
           mdays.add(new JLabel(Integer.toString(i+1)));
            }
        
        mdays.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        mon.add(mdays);
        return mon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Year", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Month", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
